import ROOT as root

events = 100

rdataA = root.TFile.Open("Data_A.root","recreate")
hdataA = root.TH1F("hist","hist",1,0,1)
hdataA.SetBinContent(1,events)
hdataA.SetBinError(1,10)
hdataA.Write()
rdataA.Write()
rdataA.Close()
rdataB = root.TFile.Open("Data_B.root","recreate")
hdataB = root.TH1F("hist","hist",1,0,1)
hdataB.SetBinContent(1,events)
hdataB.SetBinError(1,10)
hdataB.Write()
rdataB.Write()
rdataB.Close()
########
rbkg1A = root.TFile.Open("Bkg1_A.root","recreate")
hbkg1A = root.TH1F("hist","hist",1,0,1)
hbkg1A.SetBinContent(1,events*0.8)
hbkg1A.SetBinError(1,0)
hbkg1A.Write()
rbkg1A.Write()
rbkg1A.Close()
rbkg2B = root.TFile.Open("Bkg2_B.root","recreate")
hbkg2B = root.TH1F("hist","hist",1,0,1)
hbkg2B.SetBinContent(1,events)
hbkg2B.SetBinError(1,0)
hbkg2B.Write()
rbkg2B.Write()
rbkg2B.Close()
rsig = root.TFile.Open("Signal.root","recreate")
hsig = root.TH1F("hist","hist",1,0,1)
hsig.SetBinContent(1,events*0.2)
hsig.SetBinError(1,0)
hsig.Write()
rsig.Write()
rsig.Close()
########
rdataAB = root.TFile.Open("Data_AB.root","recreate")
hdataAB = root.TH1F("hist","hist",2,0,2)
hdataAB.SetBinContent(1,events)
hdataAB.SetBinContent(2,events)
hdataAB.SetBinError(1,10)
hdataAB.SetBinError(2,10)
hdataAB.Write()
rdataAB.Write()
rdataAB.Close()
rBkg1AB = root.TFile.Open("Bkg1_AB_prefit.root","recreate")
hBkg1AB = root.TH1F("hist","hist",2,0,2)
hBkg1AB.SetBinContent(1,events*0.8)
hBkg1AB.SetBinContent(2,0)
hBkg1AB.SetBinError(1,events*0.5*0.8)
hBkg1AB.SetBinError(2,0)
hBkg1AB.Write()
rBkg1AB.Write()
rBkg1AB.Close()
rBkg2AB = root.TFile.Open("Bkg2_AB_prefit.root","recreate")
hBkg2AB = root.TH1F("hist","hist",2,0,2)
hBkg2AB.SetBinContent(1,0)
hBkg2AB.SetBinContent(2,events)
hBkg2AB.SetBinError(1,0)
hBkg2AB.SetBinError(2,events*0.1*1.4142)
hBkg2AB.Write()
rBkg2AB.Write()
rBkg2AB.Close()
rBkg1AB = root.TFile.Open("Bkg1_AB_postfit.root","recreate")
hBkg1AB = root.TH1F("hist","hist",2,0,2)
hBkg1AB.SetBinContent(1,events)
hBkg1AB.SetBinContent(2,0)
hBkg1AB.SetBinError(1,events*0.1)
hBkg1AB.SetBinError(2,0)
hBkg1AB.Write()
rBkg1AB.Write()
rBkg1AB.Close()
rBkg2AB = root.TFile.Open("Bkg2_AB_postfit.root","recreate")
hBkg2AB = root.TH1F("hist","hist",2,0,2)
hBkg2AB.SetBinContent(1,0)
hBkg2AB.SetBinContent(2,events)
hBkg2AB.SetBinError(1,0)
hBkg2AB.SetBinError(2,events*0.1)
hBkg2AB.Write()
rBkg2AB.Write()
rBkg2AB.Close()
rsigAB = root.TFile.Open("Signal_AB_prefit.root","recreate")
hsigAB = root.TH1F("hist","hist",1,0,1)
hsigAB.SetBinContent(1,events*0.2)
hsigAB.SetBinError(1,0)
hsigAB.SetBinContent(2,0)
hsigAB.SetBinError(2,0)
hsigAB.Write()
rsigAB.Write()
rsigAB.Close()
rsigAB = root.TFile.Open("Signal_AB_postfit.root","recreate")
hsigAB = root.TH1F("hist","hist",1,0,1)
hsigAB.SetBinContent(1,events*0.2)
hsigAB.SetBinError(1,0)
hsigAB.SetBinContent(2,0)
hsigAB.SetBinError(2,0)
hsigAB.Write()
rsigAB.Write()
rsigAB.Close()
